 

services:
  catalogdb:
    container_name: catalogdb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
 
  basketdb:
    container_name: basketdb
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
  
  discountdb:
    container_name: discountdb
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discountdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:  # این خط را درست کردیم
      - backend

  OrderDb:
    container_name: OrderDb
    environment:
        SA_PASSWORD: "swN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
    - "1433:1433"
    volumes:
      - orderdbdata:/var/opt/mssql
    networks:  # این خط را درست کردیم
      - backend
 

  rabbitmq:
      container_name: rabbitmq  
      restart: always
      ports:
      - "15672:15672"
      - "5672:5672"
      

  
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always 
    ports:
      - "5050:80"   
    volumes:
      - pgadmin_data:/root/.pgadmin
    networks:
      - backend



  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "8000:8000" 
      - "9000:9000" 
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /portainer_data:/data 

  catalog.api:
    container_name: catalog.api
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "7000:8080"
    networks:
      - backend
  
        

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc:80"
      - ASPNETCORE_HTTP_PORTS=8080
      - "EventBusSettings:HostAddress=amqp://admin:admin1234@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "7001:8080"
    networks:
      - backend

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=discountdb;Port=5432;Database=discountdb;User Id=admin;Password=admin1234
    depends_on:
      - discountdb
    ports:
      - "7002:8080"
    networks:  # این خط را درست کردیم
      - backend
    


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Server=discountdb;Port=5432;Database=discountdb;User Id=admin;Password=admin1234
    depends_on:
      - discountdb
    ports:
      - "7003:80"
    networks:  # این خط را درست کردیم
      - backend

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__OrderingConnectionString=Server=OrderDb;Database=OrderDb;User Id=sa;Password=swN12345678;Trust Server Certificate=True
      - "EventBusSettings:HostAddress=amqp://admin:admin1234@rabbitmq:5672"
    depends_on:
      - OrderDb
      - rabbitmq
    ports:
      - "7004:80"
    networks:
      - backend

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - ordering.api
      - discount.api
      - catalog.api
      - basket.api
    ports:
      - "8010:80"
    networks:
      - backend

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ApiSettings:CatalogUrl=http://catalog.api:8080" 
      - "ApiSettings:BasketUrl=http://basket.api:8080" 
      - "ApiSettings:OrderingUrl=http://ordering.api"
    depends_on:
      - ordering.api
      - catalog.api
      - basket.api
    ports:
      - "8005:8080"
    networks:
      - backend

volumes:
  mongo_data:
  postgres_data:
  orderdbdata:
networks:
  backend:
   driver: bridge





